# Archivo: .streamlit/secrets.toml

ODOO_URL = "https://proyectos-gerenciando-canales.odoo.com"
ODOO_DB = "proyectos-gerenciando-canales"
ODOO_USER = "odooproyectosgerenciando@gmail.com"
ODOO_KEY = "5128740142e5be95fb506af7deb1a574cefad87f"